//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAXER.PORTAL.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class AgentLogin
    {
        public int Id { get; set; }
        [ForeignKey("AgentInformation")]
        public int AgentId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public bool IsActive { get; set; }
        public string ActivationCode { get; set; }
        public int LoginFailedCount { get; set; }
        public string LoginCode { get; set; }
    
        public virtual AgentInformation AgentInformation { get; set; }
    }
}
