//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAXER.PORTAL.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CardHolderDetail
    {
       
        [Key]
        public int Id { get; set; }
        public string CardNumber { get; set; }
        public string FaxerCode { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DOB { get; set; }
        public string HomeAddress { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public byte[] Photo { get; set; }
        public string PhotoID { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string Status { get; set; }
        public string IsPaid { get; set; }
        public Nullable<decimal> Limit { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public byte[] TimeStamp { get; set; }
        public string ReceiptNumber { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string IsAutoRecharge { get; set; }
        public Nullable<decimal> AutoRechargeAmount { get; set; }
        public int FaxerInformationId { get; set; }
    
        public virtual FaxerInformation FaxerInformation { get; set; }
        
        
    }
}
