//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAXER.PORTAL.DB
{
    using System;
    using System.Collections.Generic;

    public partial class ExchangeRate
    {
        public int Id { get; set; }
        public string CountryCode1 { get; set; }
        public string CountryCode2 { get; set; }
        public decimal CountryRate1 { get; set; }
        public decimal CountryRate2 { get; set; }
        public Nullable<decimal> FaxingFee1 { get; set; }
        public Nullable<decimal> FaxingFee2 { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }

        public TransactionTransferType TransferType { get; set; }
        public TransactionTransferMethod TransferMethod { get; set; }
        public int? AgentId { get; set; }
        public decimal Rate { get; set; }
        public decimal FromRange { get; set; }
        public decimal ToRange { get; set; }
        public int TransferFeeByCurrencyId { get; set; }
        public string SendingCurrency { get; set; }
        public string RecevingCurrency { get; set; }
    }
}
