//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAXER.PORTAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaxerLogin
    {
        public int Id { get; set; }
        public int FaxerId { get; set; }
        public string UserName { get; set; }

        public string MobileNo { get; set; }

        public string Password { get; set; }
        public bool IsActive { get; set; }
        public string ActivationCode { get; set; }
        public int LoginFailedCount { get; set; }
    
        public virtual FaxerInformation Faxer { get; set; }
    }

    public class FaxerActivityLog {

        public int Id { get; set; }
        public int FaxerId { get; set; }
        public string Source { get; set; }
        public string IpAddress { get; set; }
        public DateTime CreateDateTime { get; set; }
    }
}
