//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAXER.PORTAL.DB
{
    using System;
    using System.Collections.Generic;

    public partial class FaxerInformation
    {
        
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FaxerInformation()
        {
            //this.CardHolderDetail = new HashSet<CardHolderDetail>();
            this.FaxerLogin = new HashSet<FaxerLogin>();
            this.MFTCCardInformation = new HashSet<KiiPayPersonalWalletInformation>();
            this.ReceiversDetails = new HashSet<ReceiversDetails>();
            this.FaxerMerchantPaymentInformation = new HashSet<SenderKiiPayBusinessPaymentInformation>();
        }

        public int Id { get; set; }
        public string Email { get; set; }
        public string UserPhotoURL { get; set; }

        public DateTime? CreatedDate { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public System.DateTime? DateOfBirth { get; set; }
        public int GGender { get; set; }
        public string IdCardType { get; set; }
        public string IdCardNumber { get; set; }
        public System.DateTime IdCardExpiringDate { get; set; }
        public string IssuingCountry { get; set; }
        public string CardUrl { get; set; }
        public bool CheckAmount { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public string PhoneNumber { get; set; }
        public bool IsDeleted { get; set; }
        public bool RegisteredByAgent { get; set; }
        public string AccountNo { get; set; }
        public bool IsBusiness { get; set; }
        public string ClientToken{ get; set; }

    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<CardHolderDetail> CardHolderDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FaxerLogin> FaxerLogin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KiiPayPersonalWalletInformation> MFTCCardInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiversDetails> ReceiversDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SenderKiiPayBusinessPaymentInformation> FaxerMerchantPaymentInformation { get; set; }
    }
}
