//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAXER.PORTAL.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class KiiPayPersonalWalletWithdrawalFromAgent
    {
        public int Id { get; set; }

        #region kiiPay Personal User Info 
        [ForeignKey("KiiPayPersonalWalletInformation")]
        public int KiiPayPersonalWalletInformationId { get; set; }
        #endregion



        #region KiiPay Personal User Identification Details 
        public string IdentificationType { get; set; }
        [Required, StringLength(50)]
        public string IdNumber { get; set; }
        public DateTime IdCardExpiringDate { get; set; }
        [Required, StringLength(5)]
        public string IssuingCountryCode { get; set; }
        #endregion


        public decimal AgentCommission { get; set; }
        #region Transaction Details 
        public decimal TransactionAmount { get; set; }
        public int TransactionType { get; set; }

        public System.DateTime TransactionDate { get; set; }
        public string ReceiptNumber { get; set; }
        #endregion



         
        #region Paying Agent Information 

        public int AgentInformationId { get; set; }
        /// <summary>
        /// paying agent staff name
        /// </summary>
        public string PayingAgentName { get; set; }
        public int PayingAgentStaffId { get; set; }
        #endregion

        public virtual AgentInformation AgentInformation { get; set; }
        public virtual KiiPayPersonalWalletInformation KiiPayPersonalWalletInformation { get; set; }
    }
}
