//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAXER.PORTAL.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KiiPayBusinessInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KiiPayBusinessInformation()
        {
            this.KiiPayBusinessLogin = new HashSet<KiiPayBusinessLogin>();
            this.KiiPayBusinessWalletInformation = new HashSet<KiiPayBusinessWalletInformation>();
            this.SenderKiiPayBusinessPaymentInformation = new HashSet<SenderKiiPayBusinessPaymentInformation>();
        }
     
        public int Id { get; set; }
        #region Busines Information 

        public string BusinessName { get; set; }
        public string RegistrationNumBer { get; set; }
        public string BusinessLicenseNumber { get; set; }
        public BusinessType BusinessType { get; set; }
        public string Email { get; set; }
        public string ContactPerson { get; set; }

        public string BusinessCountry { get; set; }
        public string CountryOfIncorporation { get; set; }

        public string PhoneNumber { get; set; }
        /// <summary>
        /// Business Account No
        /// </summary>
        public string BusinessMobileNo { get; set; }


        public bool BillIsIssuedToCustomer { get; set; }
        #endregion


        #region  Business Registered Address

        public string BusinessRegisteredCountry { get; set; }
        public string BusinessRegisteredCity { get; set; }
        public string BusinessRegisteredAddress1 { get; set; }
        public string BusinessRegisteredAddress2 { get; set; }
        public string BusinessRegisteredState { get; set; }
        public string BusinessRegisteredPostalCode { get; set; }


        #endregion


        #region Business Operating address 

        public string BusinessOperationAddress1 { get; set; }
        public string BusinessOperationAddress2 { get; set; }
        public string BusinessOperationCity { get; set; }
        public string BusinessOperationState { get; set; }
        public string BusinessOperationPostalCode { get; set; }

        public string BusinessOperationCountryCode { get; set; }
        #endregion



        public string FaxNumber { get; set; }

        public string Website { get; set; }


        public bool UnCompletedProfile { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KiiPayBusinessLogin> KiiPayBusinessLogin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KiiPayBusinessWalletInformation> KiiPayBusinessWalletInformation { get; set; }

      

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SenderKiiPayBusinessPaymentInformation> SenderKiiPayBusinessPaymentInformation { get; set; }
    }
}
