//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAXER.PORTAL.DB
{
    using System;
    using System.Collections.Generic;

    public partial class KiiPayBusinessLogin
    {
        public int Id { get; set; }
        public string Username { get; set; }

        public string MobileNo { get; set; }

        public string Password { get; set; }
        public string LoginCode { get; set; }
        public bool IsActive { get; set; }
        public string ActivationCode { get; set; }
        public int LoginFailCount { get; set; }
        public int KiiPayBusinessInformationId { get; set; }
        public bool IsDeleted { get; set; }
        public string PinCode { get; set; }

        public virtual KiiPayBusinessInformation KiiPayBusinessInformation { get; set; }
    }
}
