//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAXER.PORTAL.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SenderKiiPayBusinessPaymentInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SenderKiiPayBusinessPaymentInformation()
        {
            this.SenderKiiPayBusinessPaymentTransaction = new HashSet<SenderKiiPayBusinessPaymentTransaction>();
        }

        public int Id { get; set; }
        #region sender Details (Moneyfex sender)


        public int SenderInformationId { get; set; }
        #endregion
        #region KiiPay Business Info 


        public int KiiPayBusinessInformationId { get; set; }
        #endregion

        #region Transaction Info

        public decimal PaymentAmount { get; set; }
        public string PaymentRefrence { get; set; }

        public bool EnableAutoPayment { get; set; }
        public AutoPaymentFrequency AutoPaymentFrequency { get; set; }

        public string FrequencyDetails { get; set; }
        public decimal AutoPaymentAmount { get; set; }

        #endregion

        public virtual KiiPayBusinessInformation KiiPayBusinessInformation { get; set; }
        public virtual FaxerInformation SenderInformation { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SenderKiiPayBusinessPaymentTransaction> SenderKiiPayBusinessPaymentTransaction { get; set; }
    }
    public enum AutoPaymentFrequency
    {
        [Display(Name = "No Limit")]
        NoLimitSet,
        Weekly,
        Monthly,
        Yearly
    }
}
